### ISSUE TITLE
MongoDB and Redis

### ISSUE THREAD

**Issue by breiko83** [lefthand/Node-JS-Bootstrap#3]
This is not an issue, just if you can give some explanation about the project.
Can you explain why you chose to use MongoDB and also Redis, and which features are you covering with Redis in this project and which one with MongoDb.
Thanks,
Carlo

**Comment by lefthand** [comment]
Hi Carlo, I'm happy to answer.  

I'm only using Redis for storing sessions at this point. Redis works really well for this task.  I choose MongoDB since it seems to fit into node nicely. I like that the mongo interface is all javascript so everything can be consistent.  The flexibility, speed and overall scalability of Mongo also attracted me.  I've been happy with the choice so far but I haven't ruled out using mysql or another nosql db as an option for this project.

**Comment by breiko83** [comment]
Thanks for your answer! I've just tested your framework and you've done a really good job.
I'll let you know if I will integrate it in some future project.

All the best,
Carlo
